version: "3"

services:
  eurxd:
    container_name: eurxd
    image: lcnem/eurx:next
    volumes:
      - ~/.eurx:/root/.eurx
    command: eurxd start \
      --rpc.laddr=tcp://0.0.0.0:26657 \
      --api.enable=true \
      --api.address=tcp://0.0.0.0:1317 \
      --api.enabled-unsafe-cors=true
    networks:
      default:
        ipv4_address: 192.168.10.1
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
