version: "3"

services:
  eurxd:
    container_name: eurxd
    image: lcnem/eurx
    # ports:
    #   - 1317:1317
    #   - 9090:9090
    #   - 26656:26656
    #   - 26657:26657
    volumes:
      - ~/.eurx:/root/.eurx
    command: eurxd start
    network_mode: host
    restart: always
