version: '3'

services:
  eurxdnode0:
    container_name: eurxdnode0
    image: "lcnem/eurxnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  eurxdnode1:
    container_name: eurxdnode1
    image: "lcnem/eurxnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  eurxdnode2:
    container_name: eurxdnode2
    image: "lcnem/eurxnode"
    environment:
      - ID=2
      - LOG=${LOG:-kvd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  eurxdnode3:
    container_name: eurxdnode3
    image: "lcnem/eurxnode"
    environment:
      - ID=3
      - LOG=${LOG:-kvd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/linux:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
